version: "3"
services:
  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  app:
    build: .
    # image: golang:1.21
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    working_dir: /app
    # volumes:
    #   - .:/app
    # environment:
    #   - CGO_ENABLED=1
    # command: ["go", "run", "main.go"]
    command: ["./main"]
